### ISSUE TITLE
jeecgboot-vue2配置前端项目前缀，nginx部署出现重定向404

### ISSUE THREAD

**Issue by 13249129236** [jeecgboot/jeecgboot-vue2#65]
##### 版本号：
使用的是jeecgboot-vue2

##### 问题描述：
配置publicPath和router的base后，开发环境是正常访问与重定向的；部署到nginx后，首次可以重定向，再次刷新就404。
能否官方提供配置方案参考？
##### 截图&代码：
![image](https://github.com/user-attachments/assets/b4d2be5c-5830-45b4-a419-a18d368e2930)
![image](https://github.com/user-attachments/assets/1f01548e-c538-4e78-b3e7-ff67bfc69c59)
![image](https://github.com/user-attachments/assets/21bc73bc-950f-462a-a0c5-3d2f2d5e4d02)
![image](https://github.com/user-attachments/assets/308cd22d-a12b-4b55-a173-d6209d14b1f5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
怎么配置的

**Comment by 13249129236** [comment]
> 怎么配置的
![image](https://github.com/user-attachments/assets/482cb917-500b-4ef3-98c4-134c4ddad047)
这是我的nginx配置

**Comment by zhangdaiscott** [comment]
为什么要这么配，这官方的配置方式
