### ISSUE TITLE
为什么要这么配，这官方的配置方式

### ISSUE THREAD

**Issue by 13249129236** [jeecgboot/jeecgboot-vue2#66]
为什么要这么配，这官方的配置方式

_Originally posted by @zhangdaiscott in https://github.com/jeecgboot/jeecgboot-vue2/issues/65#issuecomment-2480884022_
            请问在哪里提供了官方的配置方式呢。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043886

**Comment by 13249129236** [comment]
> http://doc.jeecg.com/2043886

您是没有看清我的问题嘛，我的问题是想给项目添加前缀，nginx同时配置前缀呢
